# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-06 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xm2cloud_cmp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('port', models.IntegerField(default=65022)),
                ('password', models.CharField(blank=True, max_length=32)),
                ('username', models.CharField(default='root', max_length=32)),
                ('authfile', models.FileField(blank=True, upload_to='sshkeys')),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('authpass', models.CharField(blank=True, default='', max_length=32)),
                ('authtype', models.CharField(choices=[('password', 'password'), ('authfile', 'authfile')], default='password', max_length=16)),
                ('protocol', models.CharField(choices=[('ssh', 'ssh'), ('vnc', 'vnc'), ('rdp', 'rdp'), ('sftp', 'sftp'), ('telnet', 'telnet')], default='ssh', max_length=32)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.Host')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='identification',
            unique_together=set([('host', 'port', 'username')]),
        ),
    ]
