# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-17 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import xm2cloud_term.common.enhance


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_term', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='id',
            field=models.CharField(auto_created=True, default=xm2cloud_term.common.enhance.get_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
