#! -*- coding: utf-8 -*-


from django.conf.urls import url


from . import views


urlpatterns = [
    url(r'^home/$', views.HomeView.as_view(),
        name='home'),

    url(r'^dashboard/$', views.DashboardView.as_view(),
        name='dashboard'),

    url(r'^clusters/$', views.ClusterListView.as_view(),
        name='clusters'),
    url(r'^cluster/create/$', views.ClusterCreateView.as_view(),
        name='cluster_create'),
    url(r'^cluster/update/(?P<id>[0-9a-z_\-]+)/$', views.ClusterUpdateView.as_view(),
        name='cluster_update'),
    url(r'^cluster/delete/(?P<id>[0-9a-z_\-]+)/$', views.ClusterDeleteView.as_view(),
        name='cluster_delete'),
    url(r'^cluster/manage/$', views.ClusterManageView.as_view(),
        name='cluster_manage'),
    url(r'^cluster/(?P<id>[0-9a-z_\-]+)/$', views.ClusterDetailView.as_view(),
        name='cluster_detail'),

    url(r'^hostgroups/$', views.HostgroupListView.as_view(),
        name='hostgroups'),
    url(r'^hostgroup/create/$', views.HostgroupCreateView.as_view(),
        name='hostgroup_create'),
    url(r'^hostgroup/update/(?P<id>[0-9a-z_\-]+)/$', views.HostgroupUpdateView.as_view(),
        name='hostgroup_update'),
    url(r'^hostgroup/delete/(?P<id>[0-9a-z_\-]+)/$', views.HostgroupDeleteView.as_view(),
        name='hostgroup_delete'),
    url(r'^hostgroup/manage/$', views.HostgroupManageView.as_view(),
        name='hostgroup_manage'),
    url(r'^hostgroup/(?P<id>[0-9a-z_\-]+)/$', views.HostgroupDetailView.as_view(),
        name='hostgroup_detail'),

    url(r'^hosts/$', views.HostListView.as_view(),
        name='hosts'),
    url(r'^host/create/$', views.HostCreateView.as_view(),
        name='host_create'),
    url(r'^host/update/(?P<id>[0-9a-z_\-]+)/$', views.HostUpdateView.as_view(),
        name='host_update'),
    url(r'^host/delete/(?P<id>[0-9a-z_\-]+)/$', views.HostDeleteView.as_view(),
        name='host_delete'),
    url(r'^host/manage/$', views.HostManageView.as_view(),
        name='host_manage'),
    url(r'^host/(?P<id>[0-9a-z_\-]+)/$', views.HostDetailView.as_view(),
        name='host_detail'),

    url(r'^iplines/$', views.IpLineListView.as_view(),
        name='iplines'),
    url(r'^ipline/create/$', views.IpLineCreateView.as_view(),
        name='ipline_create'),
    url(r'^ipline/update/(?P<id>[0-9a-z_\-]+)/$', views.IpLineUpdateView.as_view(),
        name='ipline_update'),
    url(r'^ipline/delete/(?P<id>[0-9a-z_\-]+)/$', views.IpLineDeleteView.as_view(),
        name='ipline_delete'),
    url(r'^ipline/(?P<id>[0-9a-z_\-]+)/$', views.IpLineDetailView.as_view(),
        name='ipline_detail'),

    url(r'^iplinepackages/$', views.IpLinePackageListView.as_view(),
        name='iplinepackages'),
    url(r'^iplinepackage/create/$', views.IpLinePackageCreateView.as_view(),
        name='iplinepackage_create'),
    url(r'^iplinepackage/update/(?P<id>[0-9a-z_\-]+)/$', views.IpLinePackageUpdateView.as_view(),
        name='iplinepackage_update'),
    url(r'^iplinepackage/delete/(?P<id>[0-9a-z_\-]+)/$', views.IpLinePackageDeleteView.as_view(),
        name='iplinepackage_delete'),
    url(r'^iplinepackage/(?P<id>[0-9a-z_\-]+)/$', views.IpLinePackageDetailView.as_view(),
        name='iplinepackage_detail'),

    url(r'^api/dashboardscreen/$', views.DashboardScreenListApiView.as_view(),
        name='api_dashboardscreen_list'),
    url(r'^api/dashboardscreen/create/$', views.DashboardScreenCreateApiView.as_view(),
        name='api_dashboardscreen_create'),
    url(r'^api/dashboardscreen/update/(?P<id>[0-9a-z_\-]+)/$', views.DashboardScreenUpdateApiView.as_view(),
        name='api_dashboardscreen_update'),
    url(r'^api/dashboardscreen/delete/(?P<id>[0-9a-z_\-]+)/$', views.DashboardScreenDeleteApiView.as_view(),
        name='api_dashboardscreen_delete'),

    url(r'^api/cluster/$', views.ClusterApiListView.as_view(),
        name='api_cluster_list'),
    url(r'^api/cluster/create/$', views.ClusterApiCreateView.as_view(),
        name='api_cluster_create'),
    url(r'^api/cluster/update/(?P<id>[0-9a-z_\-]+)/$', views.ClusterApiUpdateView.as_view(),
        name='api_cluster_update'),
    url(r'^api/cluster/delete/(?P<id>[0-9a-z_\-]+)/$', views.ClusterApiDeleteView.as_view(),
        name='api_cluster_delete'),

    url(r'^api/hostgroup/$', views.HostgroupApiListView.as_view(),
        name='api_hostgroup_list'),
    url(r'^api/hostgroup/create/$', views.HostgroupApiCreateView.as_view(),
        name='api_hostgroup_create'),
    url(r'^api/hostgroup/update/(?P<id>[0-9a-z_\-]+)/$', views.HostgroupApiUpdateView.as_view(),
        name='api_hostgroup_update'),
    url(r'^api/hostgroup/delete/(?P<id>[0-9a-z_\-]+)/$', views.HostgroupApiDeleteView.as_view(),
        name='api_hostgroup_delete'),

    url(r'^api/host/$', views.HostApiListView.as_view(),
        name='api_host_list'),
    url(r'^api/host/create/$', views.HostApiCreateView.as_view(),
        name='api_host_create'),
    url(r'^api/host/update/(?P<id>[0-9a-z_\-]+)/$', views.HostApiUpdateView.as_view(),
        name='api_host_update'),
    url(r'^api/host/delete/(?P<id>[0-9a-z_\-]+)/$', views.HostApiDeleteView.as_view(),
        name='api_host_delete'),

    url(r'^api/ipline/$', views.IpLineApiListView.as_view(),
        name='api_ipline_list'),
    url(r'^api/ipline/create/$', views.IpLineApiCreateView.as_view(),
        name='api_ipline_create'),
    url(r'^api/ipline/update/(?P<id>[0-9a-z_\-]+)/$', views.IpLineApiUpdateView.as_view(),
        name='api_ipline_update'),
    url(r'^api/ipline/delete/(?P<id>[0-9a-z_\-]+)/$', views.IpLineApiDeleteView.as_view(),
        name='api_ipline_delete'),

    url(r'^api/iplinepackage/$', views.IpLinePackageApiListView.as_view(),
        name='api_iplinepackage_list'),
    url(r'^api/iplinepackage/create/$', views.IpLinePackageApiCreateView.as_view(),
        name='api_iplinepackage_create'),
    url(r'^api/iplinepackage/update/(?P<id>[0-9a-z_\-]+)/$', views.IpLinePackageApiUpdateView.as_view(),
        name='api_iplinepackage_update'),
    url(r'^api/iplinepackage/delete/(?P<id>[0-9a-z_\-]+)/$', views.IpLinePackageApiDeleteView.as_view(),
        name='api_iplinepackage_delete'),
]
