"""
Django settings for xm_zoomeye_webui project.

Generated by 'django-admin startproject' using Django 1.11.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""


import os
import urllib3
import logging
import djcelery


from multiprocessing import cpu_count
from django.core.urlresolvers import reverse_lazy


djcelery.setup_loader()


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=&jh!nr+h)@6d@ewr7ay0tc#zkg-@0%^gd+e%owiht@4b7sjlv'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

ROOT_URLCONF = 'entrance.urls'

LOGIN_URL = reverse_lazy('xm2cloud_auth:login')

# Http settings
HTTP_POOL = urllib3.PoolManager(num_pools=cpu_count()*4)

# Application definition
INSTALLED_APPS = [
    'xm2cloud_auth',
    'xm2cloud_web',
    'xm2cloud_cmp',
    'xm2cloud_blog',
    'xm2cloud_term',
    'polymorphic',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'channels',
]
INSTALLED_APPS += [
    'djcelery',
    'rest_framework',
    'rest_framework_swagger',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'entrance.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'xm2cloud_ops_test',
        'USER': 'root',
        'PASSWORD': 'z6A1kaff8X4UbsjpwxseMVtWerMxiAok',
        'HOST': 'ops.xxoo.com',
        'PORT': 3306,
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/
USE_TZ = False

USE_I18N = True

USE_L10N = True

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/
STATIC_URL = '/static/'

MEDIA_URL = '/media/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_ROOT = os.path.join(BASE_DIR, 'upload_files')


# Logging settings
DJANGO_LOG_LEVEL = logging.getLevelName(logging.DEBUG)


# Email settings
EMAIL_PORT = 25

EMAIL_TIMEOUT = None

EMAIL_USE_TLS = True

EMAIL_USE_SSL = False

EMAIL_SSL_KEYFILE = None

EMAIL_SSL_CERTFILE = None

EMAIL_HOST = 'smtp.qq.com'

EMAIL_USE_LOCALTIME = True

EMAIL_SUBJECT_PREFIX = '[XM2CLOUD]'

SERVER_EMAIL = 'xmdevops@vip.qq.com'

EMAIL_HOST_USER = 'xmdevops@vip.qq.com'

EMAIL_HOST_PASSWORD = 'zdswmabhnkdpifcb'

DEFAULT_FROM_EMAIL = 'xmdevops@vip.qq.com'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'


# Rabbitmq settings
CHANNEL_RABBITMQ_SSL = False
CHANNEL_RABBITMQ_PORT = 5672
CHANNEL_RABBITMQ_DOWN_QUEUE = ''
CHANNEL_RABBITMQ_HOST = 'ops.xxoo.com'
CHANNEL_RABBITMQ_VHOST = '/event_engine'
CHANNEL_RABBITMQ_UP_QUEUE = 'event_up_queue'
CHANNEL_RABBITMQ_UP_EXCHANGE_TYPE = 'direct'
CHANNEL_RABBITMQ_DOWN_EXCHANGE_TYPE = 'topic'
CHANNEL_RABBITMQ_AUTH_USER = 'event_engine_user'
CHANNEL_RABBITMQ_UP_ROUTING_KEY = 'up_routing_key'
CHANNEL_RABBITMQ_UP_EXCHANGE = 'event_up_exchange'
CHANNEL_RABBITMQ_DOWN_ROUTING_KEY = 'down_routing_key'
CHANNEL_RABBITMQ_DOWN_EXCHANGE = 'event_down_exchange'
CHANNEL_RABBITMQ_AUTH_PASS = 'oZ38h0GoA0TehWcAPyIJqaponqo8Itv9'


# OpenTsdb settings
BACKEND_OPENTSDB_PORT = 4242
BACKEND_OPENTSDB_PROTOCOL = 'http'
BACKEND_OPENTSDB_USERNAME = ''
BACKEND_OPENTSDB_PASSWORD = ''
BACKEND_OPENTSDB_HOST = 'ops.xxoo.com'


# Celery settings
CELERY_ENABLE_UTC = False

CELERY_TIMEZONE = 'Asia/Shanghai'

CELERYD_MAX_TASKS_PER_CHILD = 40

CELERY_RESULT_SERIALIZER = 'json'

CELERY_TASK_SERIALIZER = 'msgpack'

CELERY_ACCEPT_CONTENT = ['json', 'msgpack']

CELERY_TASK_RESULT_EXPIRES = 60 * 60 * 24 * 7

CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'

CELERY_RESULT_BACKEND = 'redis://:z6A1kaff8X4UbsjpwxseMVtWerMxiAok@ops.xxoo.com:6379/1'

BROKER_URL = 'amqp://celery_engine_user:z6A1kaff8X4UbsjpwxseMVtWerMxiAok@ops.xxoo.com:5672//celery_engine'


# Channel settings
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'asgi_redis.RedisChannelLayer',
        'CONFIG': {
            'hosts': ['redis://:z6A1kaff8X4UbsjpwxseMVtWerMxiAok@ops.xxoo.com:6379/3'],
        },
        'ROUTING': 'xm2cloud_term.routing.channel_routing'
    }
}


# Cache settings
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://:z6A1kaff8X4UbsjpwxseMVtWerMxiAok@ops.xxoo.com:6379/0'
    },
    'celery': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://:z6A1kaff8X4UbsjpwxseMVtWerMxiAok@ops.xxoo.com:6379/1'
    },
    'session': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://:z6A1kaff8X4UbsjpwxseMVtWerMxiAok@ops.xxoo.com:6379/2'
    },
    'channel': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://:z6A1kaff8X4UbsjpwxseMVtWerMxiAok@ops.xxoo.com:6379/3'
    }
}

# Session settings
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "session"

# Mfa settings
MFA_USER_NAME = 'alice@google.com'
MFA_SECRET_KEY = 'JBSWY3DPEHPK3PXP'
MFA_ISSUER_NAME = 'Google Authenticator'

# Task settings
LOGGING_TASK_KEY_PREFIX = 'xm2cloud_agent::logging::key'
LOGGING_TASK_VAL_PREFIX = 'xm2cloud_agent::logging::val'
CHECKING_TASK_KEY_PREFIX = 'xm2cloud_sched::checking::key'
MONITORING_TASK_KEY_PREFIX = 'xm2cloud_agent::monitoring::key'
MONITORING_TASK_VAL_PREFIX = 'xm2cloud_agent::monitoring::val'
AGENT_HEARTBEAT_TASK_KEY_PREFIX = 'xm2cloud_agent::heartbeat::key'
ENGINE_HEARTBEAT_TASK_KEY_PREFIX = 'xm2cloud_engine::heartbeat::key'


# Restframework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
    ],
    # 'DEFAULT_AUTHENTICATIIN_CLASSES': [
    #     'xm2cloud_cmp.rest_api.v1.views.CsrfExemptSessionAuthentication'
    # ]
}
