# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-26 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
