# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-03 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0002_host_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('short_name', models.CharField(max_length=32, unique=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
