# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-03 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0003_auto_20180103_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.IpLine'),
        ),
    ]
