# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-03 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0004_host_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.IpLine'),
        ),
    ]
