# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-22 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0006_auto_20180122_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statuscheck',
            name='frequency',
        ),
    ]
