# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-22 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0007_remove_statuscheck_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscheck',
            name='reg_task',
            field=models.CharField(blank=True, choices=[(b'xm2cloud_cmp.tasks.alert.check.tasks.update_instance', b'xm2cloud_cmp.tasks.alert.check.tasks.update_instance'), (b'xm2cloud_cmp.tasks.alert.check.tasks.update_service', b'xm2cloud_cmp.tasks.alert.check.tasks.update_service')], max_length=255, null=True),
        ),
    ]
