# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0009_remove_statuscheck_last_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuscheck',
            name='compare_method',
            field=models.CharField(choices=[('max', '\u6700\u5927\u503c'), ('avg', '\u5e73\u5747\u503c'), ('min', '\u6700\u5c0f\u503c')], default='avg', max_length=32),
        ),
        migrations.AddField(
            model_name='statuscheck',
            name='from_units',
            field=models.CharField(choices=[('d', '\u5929'), ('min', '\u5206'), ('h', '\u65f6'), ('s', '\u79d2'), ('mon', '\u6708'), ('w', '\u5468'), ('y', '\u5e74')], default='min', max_length=32),
        ),
        migrations.AddField(
            model_name='statuscheck',
            name='from_value',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='statuscheck',
            name='reg_task',
            field=models.CharField(blank=True, choices=[(b'xm2cloud_cmp.tasks.alert.check.tasks.running_check', b'xm2cloud_cmp.tasks.alert.check.tasks.running_check'), (b'xm2cloud_cmp.tasks.alert.check.tasks.update_instance', b'xm2cloud_cmp.tasks.alert.check.tasks.update_instance'), (b'xm2cloud_cmp.tasks.alert.check.tasks.update_service', b'xm2cloud_cmp.tasks.alert.check.tasks.update_service')], max_length=255, null=True),
        ),
    ]
