# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0011_auto_20180123_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuscheck',
            name='max_failed_nums',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='statuscheck',
            name='successive',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
