# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 03:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0012_auto_20180123_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkinstance',
            name='notify_users',
        ),
        migrations.RemoveField(
            model_name='checkinstance',
            name='status_checks',
        ),
        migrations.RemoveField(
            model_name='checkservice',
            name='instances',
        ),
        migrations.RemoveField(
            model_name='checkservice',
            name='notify_users',
        ),
        migrations.RemoveField(
            model_name='checkservice',
            name='status_checks',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='instances',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='services',
        ),
        migrations.DeleteModel(
            name='CheckInstance',
        ),
        migrations.DeleteModel(
            name='CheckService',
        ),
        migrations.DeleteModel(
            name='NotifyUser',
        ),
    ]
