# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0013_auto_20180124_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statuscheckresult',
            name='is_succs',
        ),
        migrations.AddField(
            model_name='statuscheckresult',
            name='err_nums',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statuscheck',
            name='calculated_status',
            field=models.CharField(choices=[('PASSING', '\u6b63\u5e38\u8fd0\u884c'), ('FAILING', '\u6301\u7eed\u5f02\u5e38')], default='PASSING', max_length=64),
        ),
    ]
