# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0015_auto_20180124_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statuscheck',
            name='importance',
        ),
    ]
