# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0017_auto_20180125_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statuscheck',
            name='max_failed_nums',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='min_series_nums',
        ),
        migrations.AlterField(
            model_name='statuscheck',
            name='from_units',
            field=models.CharField(choices=[('d', '\u5929'), ('min', '\u5206\u949f'), ('h', '\u5c0f\u65f6'), ('s', '\u79d2'), ('mon', '\u6708'), ('w', '\u5468'), ('y', '\u5e74')], default='min', max_length=32),
        ),
    ]
