# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0018_auto_20180125_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkhostresult',
            name='check_status',
            field=models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('PASSING', 'PASSING'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR')], default='PASSING', max_length=64),
        ),
        migrations.AlterField(
            model_name='statuscheck',
            name='calculated_status',
            field=models.CharField(choices=[('PASSING', 'PASSING'), ('FAILING', 'FAILING'), ('EXCEPTION', 'EXCEPTION'), ('INTERMITTENT', 'INTERMITTENT')], default='PASSING', max_length=64),
        ),
        migrations.AlterField(
            model_name='statuscheck',
            name='compare_method',
            field=models.CharField(choices=[('avges', 'avg'), ('mines', 'min'), ('maxes', 'max')], default='avges', max_length=32),
        ),
        migrations.AlterField(
            model_name='statuscheck',
            name='from_units',
            field=models.CharField(choices=[('d', 'days'), ('min', 'minutes'), ('h', 'hours'), ('s', 'seconds'), ('mon', 'monthes'), ('w', 'weeks'), ('y', 'years')], default='min', max_length=32),
        ),
        migrations.AlterField(
            model_name='statuscheck',
            name='reg_task',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='statuscheck',
            name='successive',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
