# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0019_auto_20180125_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statuscheckresult',
            options={},
        ),
        migrations.AlterField(
            model_name='statuscheck',
            name='reg_task',
            field=models.CharField(blank=True, choices=[(b'xm2cloud_cmp.tasks.alert.check.tasks.running_check', b'xm2cloud_cmp.tasks.alert.check.tasks.running_check')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='statuscheckresult',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='statuscheckresult',
            name='sta_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterIndexTogether(
            name='statuscheckresult',
            index_together=set([]),
        ),
    ]
