# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0021_auto_20180125_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuscheckresult',
            name='end_time',
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='statuscheckresult',
            name='sta_time',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
