# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0022_auto_20180126_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkhostresult',
            name='check_result',
        ),
        migrations.RemoveField(
            model_name='checkhostresult',
            name='host',
        ),
        migrations.DeleteModel(
            name='CheckHostResult',
        ),
    ]
