# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-26 02:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0023_auto_20180126_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckHostResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sta_time', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('sub_metric', models.TextField(null=True)),
                ('messages', models.TextField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('sta_status', models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('PASSING', 'PASSING'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR')], default='PASSING', max_length=64)),
                ('end_status', models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('PASSING', 'PASSING'), ('WARNING', 'WARNING'), ('ERROR', 'ERROR')], max_length=64, null=True)),
                ('alert_status', models.CharField(choices=[('RELIEVED', 'RELIEVED'), ('IGNORED', 'IGNORED'), ('ALERTING', 'ALERTING')], default='ALERTING', max_length=64)),
                ('check_result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.StatusCheckResult')),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.Host')),
            ],
            options={
                'ordering': ['-end_time'],
            },
        ),
    ]
