# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-27 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0025_auto_20180126_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notifytime', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('notice_way', models.CharField(default='email', max_length=32)),
                ('alarms_way', models.CharField(default='', max_length=32)),
                ('is_success', models.BooleanField(default=False)),
                ('retrytimes', models.IntegerField(default=0)),
                ('checkhostresult', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.CheckHostResult')),
            ],
        ),
        migrations.AlterField(
            model_name='statuscheck',
            name='reg_task',
            field=models.CharField(blank=True, choices=[(b'xm2cloud_cmp.tasks.alert.graphite_alert_dispatcher', b'xm2cloud_cmp.tasks.alert.graphite_alert_dispatcher'), (b'xm2cloud_cmp.tasks.alert.http_alert_dispatcher', b'xm2cloud_cmp.tasks.alert.http_alert_dispatcher'), (b'xm2cloud_cmp.tasks.alert.port_alert_dispatcher', b'xm2cloud_cmp.tasks.alert.port_alert_dispatcher'), (b'xm2cloud_cmp.tasks.alert.service_alert_dispatcher', b'xm2cloud_cmp.tasks.alert.service_alert_dispatcher'), (b'xm2cloud_cmp.tasks.check.running_check', b'xm2cloud_cmp.tasks.check.running_check')], max_length=255, null=True),
        ),
    ]
