# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-27 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0026_auto_20180127_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkhostresult',
            name='end_values',
            field=models.TextField(null=True),
        ),
    ]
