# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 02:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0027_checkhostresult_end_values'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-notifytime']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='notifytime',
            field=models.DateTimeField(auto_created=True, db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='statuscheck',
            name='reg_task',
            field=models.CharField(blank=True, choices=[(b'xm2cloud_cmp.tasks.alert.graphite_alert_dispatcher', b'xm2cloud_cmp.tasks.alert.graphite_alert_dispatcher'), (b'xm2cloud_cmp.tasks.alert.http_alert_dispatcher', b'xm2cloud_cmp.tasks.alert.http_alert_dispatcher'), (b'xm2cloud_cmp.tasks.alert.port_alert_dispatcher', b'xm2cloud_cmp.tasks.alert.port_alert_dispatcher'), (b'xm2cloud_cmp.tasks.alert.service_alert_dispatcher', b'xm2cloud_cmp.tasks.alert.service_alert_dispatcher'), (b'xm2cloud_cmp.tasks.check.running_check', b'xm2cloud_cmp.tasks.check.running_check'), (b'xm2cloud_cmp.tasks.clean.database_cleanup', b'xm2cloud_cmp.tasks.clean.database_cleanup')], max_length=255, null=True),
        ),
    ]
