# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-04 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0028_auto_20180131_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashBoardScreen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='xm2cloud_cmp.DashBoardScreen')),
            ],
        ),
        migrations.CreateModel(
            name='DashBoardScreenTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charttype', models.CharField(choices=[('table', 'table'), ('line', 'line'), ('hotmap', 'hotmap'), ('pie', 'pie'), ('area', 'area')], default='line', max_length=32)),
                ('gh_target', models.TextField()),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='xm2cloud_cmp.DashBoardScreen')),
            ],
        ),
    ]
