# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-04 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0029_dashboardscreen_dashboardscreentarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardscreentarget',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
