# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0030_dashboardscreentarget_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SSHIdentification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('authtype', models.CharField(choices=[('authfile', 'authfile'), ('password', 'password')], default='password', max_length=16)),
                ('username', models.CharField(default='root', max_length=32)),
                ('password', models.CharField(blank=True, max_length=32)),
                ('authfile', models.FileField(blank=True, upload_to='ssh_keys')),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
