# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0031_sshidentification'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='auth',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.SSHIdentification'),
        ),
        migrations.AddField(
            model_name='host',
            name='ssh_port',
            field=models.IntegerField(default=22),
        ),
    ]
