# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0032_auto_20180305_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.SSHIdentification'),
        ),
    ]
