# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-10 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0034_sshidentification_authpass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshidentification',
            name='authpass',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
