# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-27 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0036_region_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='manufacturer',
        ),
    ]
