# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-28 11:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0037_remove_region_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='expiry_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 3, 28, 11, 39, 2, 699570, tzinfo=utc)),
        ),
    ]
