# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-29 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0001_initial'),
        ('xm2cloud_cmp', '0039_auto_20180328_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTask',
            fields=[
                ('periodictask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djcelery.PeriodicTask')),
                ('reg_task', models.CharField(blank=True, choices=[(b'xm2cloud_cmp.tasks.alert.port_alert_dispatcher', b'xm2cloud_cmp.tasks.alert.port_alert_dispatcher'), (b'xm2cloud_cmp.tasks.clean.database_cleanup', b'xm2cloud_cmp.tasks.clean.database_cleanup'), (b'xm2cloud_cmp.tasks.alert.service_alert_dispatcher', b'xm2cloud_cmp.tasks.alert.service_alert_dispatcher'), (b'xm2cloud_cmp.tasks.check.running_check', b'xm2cloud_cmp.tasks.check.running_check'), (b'xm2cloud_cmp.tasks.alert.http_alert_dispatcher', b'xm2cloud_cmp.tasks.alert.http_alert_dispatcher'), (b'xm2cloud_cmp.tasks.alert.graphite_alert_dispatcher', b'xm2cloud_cmp.tasks.alert.graphite_alert_dispatcher')], max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=('djcelery.periodictask',),
        ),
        migrations.AlterField(
            model_name='statuscheck',
            name='reg_task',
            field=models.CharField(blank=True, choices=[(b'xm2cloud_cmp.tasks.alert.port_alert_dispatcher', b'xm2cloud_cmp.tasks.alert.port_alert_dispatcher'), (b'xm2cloud_cmp.tasks.clean.database_cleanup', b'xm2cloud_cmp.tasks.clean.database_cleanup'), (b'xm2cloud_cmp.tasks.alert.service_alert_dispatcher', b'xm2cloud_cmp.tasks.alert.service_alert_dispatcher'), (b'xm2cloud_cmp.tasks.check.running_check', b'xm2cloud_cmp.tasks.check.running_check'), (b'xm2cloud_cmp.tasks.alert.http_alert_dispatcher', b'xm2cloud_cmp.tasks.alert.http_alert_dispatcher'), (b'xm2cloud_cmp.tasks.alert.graphite_alert_dispatcher', b'xm2cloud_cmp.tasks.alert.graphite_alert_dispatcher')], max_length=255, null=True),
        ),
    ]
