# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-29 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0040_auto_20180329_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttask',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='reporttask',
            name='reg_task',
            field=models.CharField(blank=True, choices=[(b'xm2cloud_cmp.tasks.report.monitoring_detailed', b'xm2cloud_cmp.tasks.report.monitoring_detailed'), (b'xm2cloud_cmp.tasks.report.monitoring_overview', b'xm2cloud_cmp.tasks.report.monitoring_overview'), (b'xm2cloud_cmp.tasks.report.resources_occupy_low', b'xm2cloud_cmp.tasks.report.resources_occupy_low'), (b'xm2cloud_cmp.tasks.report.codedeploy_overview', b'xm2cloud_cmp.tasks.report.codedeploy_overview'), (b'xm2cloud_cmp.tasks.report.resources_occupy_high', b'xm2cloud_cmp.tasks.report.resources_occupy_high')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='statuscheck',
            name='reg_task',
            field=models.CharField(blank=True, choices=[(b'xm2cloud_cmp.tasks.check.running_check', b'xm2cloud_cmp.tasks.check.running_check')], max_length=255, null=True),
        ),
    ]
