# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-31 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0043_auto_20180331_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttask',
            name='task_type',
            field=models.CharField(choices=[('monitoring_overview', 'monitoring_overview'), ('monitoring_detailed', 'monitoring_detailed'), ('codedeploy_overview', 'codedeploy_overview'), ('resources_occupy_low', 'resources_occupy_low'), ('resources_occupy_high', 'resources_occupy_high')], default='monitoring_overview', max_length=64),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='task_id',
            field=models.CharField(blank=True, default=uuid.UUID('1d59c458-4c57-40ed-a226-7b8af0224487'), max_length=36),
        ),
        migrations.AlterField(
            model_name='reporttask',
            name='fromdate',
            field=models.CharField(blank=True, choices=[(b'02:34_20180330', 'last_day'), (b'02:34_20180324', 'last_week'), (b'02:34_20180106', 'last_quarter'), (b'02:34_20170429', 'last_year')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='reporttask',
            name='task_id',
            field=models.CharField(blank=True, default=uuid.UUID('45f59e15-c50f-4662-b0a0-50285426c469'), max_length=36),
        ),
    ]
