# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-31 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0044_auto_20180331_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttask',
            name='datefrom',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='task_id',
            field=models.CharField(blank=True, default=uuid.UUID('96274ce4-a8d2-467e-945c-713deaf10b2a'), max_length=36),
        ),
        migrations.AlterField(
            model_name='reporttask',
            name='fromdate',
            field=models.CharField(blank=True, choices=[('-7', 'last_week'), ('-1', 'last_day'), ('-84', 'last_quarter'), ('-336', 'last_year')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='reporttask',
            name='task_id',
            field=models.CharField(blank=True, default=uuid.UUID('641d6a6e-0ae1-4962-996a-76fa90a4c45c'), max_length=36),
        ),
        migrations.AlterField(
            model_name='reporttask',
            name='task_type',
            field=models.CharField(choices=[('monitoring_overview', 'monitoring_overview'), ('monitoring_detailed', 'monitoring_detailed'), ('codedeploy_overview', 'codedeploy_overview'), ('resources_occupy_low', 'resources_occupy_low'), ('resources_occupy_high', 'resources_occupy_high')], max_length=64),
        ),
    ]
