# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-04 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0046_auto_20180331_2102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporting',
            options={'ordering': ['-create_time']},
        ),
        migrations.AlterModelOptions(
            name='reporttask',
            options={'ordering': ['-create_time']},
        ),
        migrations.RemoveField(
            model_name='reporting',
            name='reporttime',
        ),
        migrations.RemoveField(
            model_name='reporttask',
            name='datefrom',
        ),
        migrations.RemoveField(
            model_name='reporttask',
            name='fromdate',
        ),
        migrations.AddField(
            model_name='reporting',
            name='context',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='reporting',
            name='create_time',
            field=models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reporttask',
            name='create_time',
            field=models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reporttask',
            name='period',
            field=models.CharField(choices=[('last_day', 'last_day'), ('last_week', 'last_week'), ('last_quarter', 'last_quarter'), ('last_year', 'last_year')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='reporting',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reporttask',
            name='reg_task',
            field=models.CharField(choices=[(b'xm2cloud_cmp.tasks.report.running_report', b'xm2cloud_cmp.tasks.report.running_report')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reporttask',
            name='task_type',
            field=models.CharField(choices=[('monitoring_overview', 'monitoring_overview'), ('monitoring_detailed', 'monitoring_detailed'), ('codedeploy_overview', 'codedeploy_overview'), ('resources_occupy_low', 'resources_occupy_low'), ('resources_occupy_high', 'resources_occupy_high')], max_length=64, null=True),
        ),
    ]
