# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-04 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0048_reporting_template_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='agentstatus',
        ),
        migrations.RemoveField(
            model_name='host',
            name='heartbeatstatus',
        ),
        migrations.RemoveField(
            model_name='host',
            name='vmstatus',
        ),
        migrations.AlterField(
            model_name='host',
            name='ssh_port',
            field=models.IntegerField(default=65022),
        ),
    ]
