# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-04 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0052_auto_20180404_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='line',
        ),
        migrations.AddField(
            model_name='host',
            name='iplines',
            field=models.ManyToManyField(to='xm2cloud_cmp.IpLine'),
        ),
    ]
