# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-04 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0055_ipline_is_preferred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipline',
            name='is_preferred',
            field=models.BooleanField(default=False),
        ),
    ]
