# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-04 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0056_auto_20180404_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipline',
            name='band_type',
            field=models.CharField(choices=[('bandwidth', 'bandwidth'), ('shareband', 'shareband')], default='bandwidth', max_length=32),
        ),
    ]
