# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-04 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0059_remove_ipline_band_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='metric_uuid',
            field=models.UUIDField(default=b'f352c284-19f3-44ef-927e-8ad2eabdae94'),
        ),
    ]
