# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-04 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0060_host_metric_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='OemInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('oemid', models.CharField(max_length=128, unique=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='GraphiteStatusCheck',
        ),
        migrations.DeleteModel(
            name='HttpStatusCheck',
        ),
        migrations.DeleteModel(
            name='PortStatusCheck',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='calculated_status',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='compare_method',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='critical_value',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='error_value',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='from_units',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='from_value',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='password',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='regexp_text',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='req_timeout',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='ssl_enabled',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='status_code',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='successive',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='username',
        ),
        migrations.RemoveField(
            model_name='statuscheck',
            name='warning_value',
        ),
        migrations.AddField(
            model_name='statuscheck',
            name='triggers',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='checkhostresult',
            name='alert_status',
            field=models.CharField(choices=[('alerting', 'alerting'), ('ignored', 'ignored'), ('relieved', 'relieved')], default='alerting', max_length=64),
        ),
        migrations.AlterField(
            model_name='checkhostresult',
            name='end_status',
            field=models.CharField(choices=[('passing', 'passing'), ('warning', 'warning'), ('error', 'error'), ('critical', 'critical')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='checkhostresult',
            name='sta_status',
            field=models.CharField(choices=[('passing', 'passing'), ('warning', 'warning'), ('error', 'error'), ('critical', 'critical')], default='passing', max_length=64),
        ),
        migrations.AlterField(
            model_name='dashboardscreentarget',
            name='charttype',
            field=models.CharField(choices=[('pie', 'pie'), ('line', 'line'), ('area', 'area'), ('table', 'table'), ('hotmap', 'hotmap')], default='line', max_length=32),
        ),
        migrations.AlterField(
            model_name='host',
            name='metric_uuid',
            field=models.UUIDField(default=b'e1dd7820-a942-4fb4-9421-87f69cb28384'),
        ),
        migrations.AlterField(
            model_name='sshidentification',
            name='authtype',
            field=models.CharField(choices=[('password', 'password'), ('authfile', 'authfile')], default='password', max_length=16),
        ),
        migrations.CreateModel(
            name='GraphiteStatusCheck',
            fields=[
                ('statuscheck_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='xm2cloud_cmp.StatusCheck')),
            ],
            bases=('xm2cloud_cmp.statuscheck',),
        ),
        migrations.CreateModel(
            name='HttpStatusCheck',
            fields=[
                ('statuscheck_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='xm2cloud_cmp.StatusCheck')),
                ('endpoint', models.TextField(blank=True, null=True)),
                ('username', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('regexp_text', models.TextField(blank=True, null=True)),
                ('status_code', models.TextField(default=200, null=True)),
                ('req_timeout', models.IntegerField(default=30, null=True)),
                ('ssl_enabled', models.BooleanField(default=False)),
            ],
            bases=('xm2cloud_cmp.statuscheck',),
        ),
        migrations.CreateModel(
            name='PortStatusCheck',
            fields=[
                ('statuscheck_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='xm2cloud_cmp.StatusCheck')),
            ],
            bases=('xm2cloud_cmp.statuscheck',),
        ),
        migrations.AlterField(
            model_name=b'StatusCheckResult',
            name='status_check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.StatusCheck'),
        ),
        migrations.AlterField(
            model_name=b'StatusCheckResult',
            name='status_check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.StatusCheck'),
        ),
        migrations.AlterField(
            model_name=b'StatusCheckResult',
            name='status_check',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.StatusCheck'),
        ),
    ]
