# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-04 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0061_auto_20180504_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='metric_uuid',
            field=models.UUIDField(default=b'915fcd19-d6f8-4d13-ab19-a552c6f74318'),
        ),
    ]
