# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-04 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0062_auto_20180504_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='metric_uuid',
            field=models.UUIDField(default=b'5dac1518-e078-47ac-845c-44a013d7a75c'),
        ),
    ]
