# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-04 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0063_auto_20180505_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='metric_uuid',
            field=models.UUIDField(default=b'b3d928b8-b046-4f1c-9354-e52118493df4'),
        ),
    ]
