# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-05 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0064_auto_20180505_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='metric_uuid',
            field=models.UUIDField(default=b'10cb3e59-0513-4014-9a05-7593acd0306b'),
        ),
    ]
