# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-07 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0065_auto_20180505_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='metric_uuid',
            field=models.UUIDField(default=b'3f8de392-dbbc-4e1a-ab41-32871cad9263'),
        ),
    ]
