# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-07 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0068_auto_20180507_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='metric_uuid',
            field=models.UUIDField(default=b'5417b381-db7e-468f-9429-c97282cd7d35'),
        ),
    ]
