# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-07 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0069_auto_20180507_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='metric_uuid',
            field=models.UUIDField(default=b'2c47390b-16c6-46c0-9de4-e52a1c83f348'),
        ),
    ]
