# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-07 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0071_auto_20180507_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='metric_uuid',
            field=models.UUIDField(default=b'6609daa9-d14b-4ed5-9ac5-380cf12748a4'),
        ),
    ]
