# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-07 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0074_auto_20180507_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='metric_uuid',
            field=models.UUIDField(default=b'3bacec45-fd23-4a3c-ac6e-aecfde1401cd'),
        ),
    ]
