# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-07 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0075_auto_20180507_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='metric_uuid',
            field=models.UUIDField(default=b'c0ea57d4-d066-43b0-85af-7b0eb38cd311'),
        ),
    ]
