# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-07 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0076_auto_20180507_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='metric_uuid',
            field=models.UUIDField(default=b'5e2bb01c-9421-412a-8bce-b466339ad19f'),
        ),
    ]
