# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-09 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0077_auto_20180507_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='metric_uuid',
            field=models.UUIDField(default=b'735a7005-7bc3-4702-8412-56ad9885d0ce'),
        ),
    ]
