# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-09 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0078_auto_20180509_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='metric_uuid',
            field=models.UUIDField(default=b'd46c5db5-4fa0-4642-9e75-12a6e280b1a3'),
        ),
    ]
