# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-09 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0079_auto_20180509_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='metric_uuid',
            field=models.UUIDField(default=b'b77728d8-139c-408f-bea8-1da304189d1d'),
        ),
    ]
