# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-06 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertContact',
            fields=[
                ('id', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertContactGroup',
            fields=[
                ('id', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=128)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClusterContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.Cluster')),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('short_name', models.CharField(max_length=32, unique=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DashBoardScreen',
            fields=[
                ('id', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='xm2cloud_cmp.DashBoardScreen')),
            ],
        ),
        migrations.CreateModel(
            name='DashBoardScreenTarget',
            fields=[
                ('id', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('target', models.CharField(default='', max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('charttype', models.CharField(choices=[('line', 'line'), ('pie', 'pie'), ('area', 'area'), ('table', 'table'), ('hotmap', 'hotmap')], default='line', max_length=32)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='xm2cloud_cmp.DashBoardScreen')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=128)),
                ('vmcpu', models.IntegerField(blank=True, default=4)),
                ('vmmem', models.IntegerField(blank=True, default=4)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('expiry_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('bill_method', models.SmallIntegerField(choices=[(0, '\u5305\u5e74/\u5305\u6708'), (1, '\u6d41\u91cf/\u8ba1\u7b97')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=128)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('alertcontactgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.AlertContactGroup')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.Cluster')),
            ],
        ),
        migrations.CreateModel(
            name='HostGroupContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('hostgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.HostGroup')),
            ],
        ),
        migrations.CreateModel(
            name='IpLine',
            fields=[
                ('id', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('band', models.IntegerField(blank=True, default=30)),
                ('is_preferred', models.BooleanField(default=False)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('line', models.CharField(choices=[('BGP', 'BGP'), ('\u79fb\u52a8', '\u79fb\u52a8'), ('\u8054\u901a', '\u8054\u901a'), ('\u7535\u4fe1', '\u7535\u4fe1'), ('\u5176\u5b83', '\u5176\u5b83')], default='BGP', max_length=128)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.Host')),
            ],
        ),
        migrations.CreateModel(
            name='IpLinePackage',
            fields=[
                ('id', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('band', models.IntegerField(blank=True, default=200)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('line', models.CharField(choices=[('\u79fb\u52a8', '\u79fb\u52a8'), ('\u8054\u901a', '\u8054\u901a'), ('\u7535\u4fe1', '\u7535\u4fe1'), ('\u5176\u5b83', '\u5176\u5b83')], default='\u79fb\u52a8', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('short_name', models.CharField(max_length=32, unique=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('website', models.CharField(blank=True, default='#', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OemInfo',
            fields=[
                ('id', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(default='', max_length=255)),
                ('oemid', models.CharField(max_length=128, unique=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('kernel', models.CharField(choices=[('UNIX', 'UNIX'), ('WINS', 'WINS')], default='UNIX', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.Continent')),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('contents', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('parameters', models.TextField(blank=True, default='')),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('interpreter', models.CharField(choices=[('sh', 'sh'), ('python', 'python'), ('ruby', 'ruby'), ('perl', 'perl')], default='sh', max_length=32)),
                ('platform', models.CharField(choices=[('linux', 'linux'), ('windows', 'windows')], default='linux', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ScriptGroup',
            fields=[
                ('id', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScriptLog',
            fields=[
                ('id', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('triggermode', models.SmallIntegerField(choices=[(0, '\u81ea\u52a8\u89e6\u53d1'), (1, '\u624b\u52a8\u89e6\u53d1')], default=1)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.Cluster')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.Host')),
                ('hostgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.HostGroup')),
                ('script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.Script')),
            ],
        ),
        migrations.AddField(
            model_name='script',
            name='scriptgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.ScriptGroup'),
        ),
        migrations.AddField(
            model_name='ipline',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.IpLinePackage'),
        ),
        migrations.AddField(
            model_name='host',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.Region'),
        ),
        migrations.AddField(
            model_name='host',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.Manufacturer'),
        ),
        migrations.AddField(
            model_name='host',
            name='hostgroups',
            field=models.ManyToManyField(to='xm2cloud_cmp.HostGroup'),
        ),
        migrations.AddField(
            model_name='host',
            name='oems',
            field=models.ManyToManyField(to='xm2cloud_cmp.OemInfo'),
        ),
        migrations.AddField(
            model_name='host',
            name='vmos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.OperatingSystem'),
        ),
        migrations.AddField(
            model_name='alertcontact',
            name='alertcontactgroups',
            field=models.ManyToManyField(to='xm2cloud_cmp.AlertContactGroup'),
        ),
    ]
