# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-14 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertContact',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertContactGroup',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=128)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('short_name', models.CharField(max_length=32, unique=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DashBoardScreen',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='xm2cloud_cmp.DashBoardScreen')),
            ],
        ),
        migrations.CreateModel(
            name='DashBoardScreenTarget',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('target', models.CharField(default='', max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('charttype', models.CharField(choices=[('line', 'line'), ('pie', 'pie'), ('area', 'area'), ('table', 'table'), ('hotmap', 'hotmap')], default='line', max_length=32)),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='xm2cloud_cmp.DashBoardScreen')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=128)),
                ('vmcpu', models.IntegerField(blank=True, default=4)),
                ('vmmem', models.IntegerField(blank=True, default=4)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('expiry_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=128)),
                ('ports', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('alertcontactgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.AlertContactGroup')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.Cluster')),
            ],
        ),
        migrations.CreateModel(
            name='IpLine',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('band', models.IntegerField(blank=True, default=30)),
                ('is_preferred', models.BooleanField(default=False)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(choices=[('BGP', 'BGP'), ('\u79fb\u52a8', '\u79fb\u52a8'), ('\u8054\u901a', '\u8054\u901a'), ('\u7535\u4fe1', '\u7535\u4fe1'), ('\u5176\u5b83', '\u5176\u5b83')], default='BGP', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='IpLinePackage',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('band', models.IntegerField(blank=True, default=200)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('website', models.URLField(default='')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('short_name', models.CharField(max_length=32, unique=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OemInfo',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('oemid', models.CharField(max_length=128, unique=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('type', models.CharField(default='linux', max_length=64)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.Continent')),
            ],
        ),
        migrations.AddField(
            model_name='ipline',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.IpLinePackage'),
        ),
        migrations.AddField(
            model_name='host',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.Region'),
        ),
        migrations.AddField(
            model_name='host',
            name='firm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.Manufacturer'),
        ),
        migrations.AddField(
            model_name='host',
            name='hostgroups',
            field=models.ManyToManyField(to='xm2cloud_cmp.HostGroup'),
        ),
        migrations.AddField(
            model_name='host',
            name='iplines',
            field=models.ManyToManyField(to='xm2cloud_cmp.IpLine'),
        ),
        migrations.AddField(
            model_name='host',
            name='vmos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.OperatingSystem'),
        ),
        migrations.AddField(
            model_name='alertcontact',
            name='alertcontactgroups',
            field=models.ManyToManyField(to='xm2cloud_cmp.AlertContactGroup'),
        ),
    ]
