# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-07 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptlog',
            name='user_script',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='scriptlog',
            name='triggermode',
            field=models.SmallIntegerField(choices=[(0, '\u624b\u52a8\u6267\u884c'), (1, '\u5b9a\u65f6\u4efb\u52a1'), (2, '\u53d1\u751f\u544a\u8b66'), (3, '\u544a\u8b66\u89e3\u9664')], default=0),
        ),
    ]
