# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-15 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0003_auto_20180514_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.Cluster')),
            ],
        ),
        migrations.CreateModel(
            name='HostGroupContext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='host',
            name='iplines',
        ),
        migrations.RemoveField(
            model_name='hostgroup',
            name='ports',
        ),
        migrations.AddField(
            model_name='ipline',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.Host'),
        ),
        migrations.AddField(
            model_name='iplinepackage',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='hostgroupcontext',
            name='hostgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.HostGroup'),
        ),
    ]
