# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-07 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0004_auto_20180607_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptlog',
            name='script_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
