# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-15 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0004_auto_20180515_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='oems',
            field=models.ManyToManyField(to='xm2cloud_cmp.OemInfo'),
        ),
        migrations.AddField(
            model_name='oeminfo',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
