# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-16 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0005_auto_20180515_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='website',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
    ]
