# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-16 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0006_auto_20180516_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatingsystem',
            name='type',
        ),
        migrations.AddField(
            model_name='operatingsystem',
            name='kernel',
            field=models.CharField(choices=[('UNIX', 'UNIX'), ('WINS', 'WINS')], default='UNIX', max_length=32),
        ),
    ]
