# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-18 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0007_auto_20180516_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipline',
            old_name='name',
            new_name='line',
        ),
        migrations.AddField(
            model_name='iplinepackage',
            name='line',
            field=models.CharField(choices=[('\u79fb\u52a8', '\u79fb\u52a8'), ('\u8054\u901a', '\u8054\u901a'), ('\u7535\u4fe1', '\u7535\u4fe1'), ('\u5176\u5b83', '\u5176\u5b83')], default='\u79fb\u52a8', max_length=128),
        ),
    ]
