# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-11 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0007_auto_20180608_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptlog',
            name='run_parameters',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scriptlog',
            name='run_timeout',
            field=models.IntegerField(blank=True, default=300),
        ),
    ]
