# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-11 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0008_auto_20180611_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptlog',
            name='run_interpreter',
            field=models.CharField(choices=[('sh', 'sh'), ('python', 'python'), ('ruby', 'ruby'), ('perl', 'perl')], default='sh', max_length=32),
        ),
        migrations.AddField(
            model_name='scriptlog',
            name='run_platform',
            field=models.CharField(choices=[('linux', 'linux'), ('windows', 'windows')], default='linux', max_length=32),
        ),
    ]
