# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-15 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0010_timedtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='timedtask',
            name='sevent_uuid',
            field=models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=36, unique=True),
        ),
    ]
