# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-15 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0012_timedcrontab_timedinterval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timedcrontab',
            name='crontab',
        ),
        migrations.RemoveField(
            model_name='timedinterval',
            name='interval',
        ),
        migrations.DeleteModel(
            name='TimedCrontab',
        ),
        migrations.DeleteModel(
            name='TimedInterval',
        ),
    ]
