# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-17 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0013_auto_20180615_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptlog',
            name='timedtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.TimedTask'),
        ),
    ]
