# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-24 00:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xm2cloud_cmp', '0014_scriptlog_timedtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskWorkFlow',
            fields=[
                ('id', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkFlowTask',
            fields=[
                ('id', models.CharField(auto_created=True, default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('with_timeout', models.SmallIntegerField(choices=[(0, '\u6302\u8d77\u7f16\u6392\u4efb\u52a1'), (1, '\u5ffd\u7565\u7ee7\u7eed\u6267\u884c')], default=0)),
                ('with_failure', models.SmallIntegerField(choices=[(0, '\u6302\u8d77\u7f16\u6392\u4efb\u52a1'), (1, '\u5ffd\u7565\u7ee7\u7eed\u6267\u884c')], default=0)),
                ('with_unknown', models.SmallIntegerField(choices=[(0, '\u6302\u8d77\u7f16\u6392\u4efb\u52a1'), (1, '\u5ffd\u7565\u7ee7\u7eed\u6267\u884c')], default=0)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.Cluster')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.Host')),
                ('hostgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.HostGroup')),
                ('next_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.WorkFlowTask')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('script', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.Script')),
                ('taskworkflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.TaskWorkFlow')),
            ],
        ),
    ]
