# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-24 17:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xm2cloud_cmp', '0015_taskworkflow_workflowtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskworkflow',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
