# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-29 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0017_updatelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatelog',
            name='sevent_uuid',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=36),
        ),
        migrations.AlterField(
            model_name='updatelog',
            name='host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.Host'),
        ),
    ]
