# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-17 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import xm2cloud_cmp.common.enhance


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0020_auto_20180629_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardscreen',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='dashboardscreentarget',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='alertcontact',
            name='id',
            field=models.CharField(auto_created=True, default=xm2cloud_cmp.common.enhance.get_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='alertcontactgroup',
            name='id',
            field=models.CharField(auto_created=True, default=xm2cloud_cmp.common.enhance.get_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='id',
            field=models.CharField(auto_created=True, default=xm2cloud_cmp.common.enhance.get_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='continent',
            name='id',
            field=models.CharField(auto_created=True, default=xm2cloud_cmp.common.enhance.get_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dashboardscreen',
            name='id',
            field=models.CharField(auto_created=True, default=xm2cloud_cmp.common.enhance.get_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dashboardscreentarget',
            name='id',
            field=models.CharField(auto_created=True, default=xm2cloud_cmp.common.enhance.get_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='host',
            name='id',
            field=models.CharField(auto_created=True, default=xm2cloud_cmp.common.enhance.get_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hostgroup',
            name='id',
            field=models.CharField(auto_created=True, default=xm2cloud_cmp.common.enhance.get_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ipline',
            name='id',
            field=models.CharField(auto_created=True, default=xm2cloud_cmp.common.enhance.get_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='iplinepackage',
            name='id',
            field=models.CharField(auto_created=True, default=xm2cloud_cmp.common.enhance.get_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='id',
            field=models.CharField(auto_created=True, default=xm2cloud_cmp.common.enhance.get_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='oeminfo',
            name='id',
            field=models.CharField(auto_created=True, default=xm2cloud_cmp.common.enhance.get_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='operatingsystem',
            name='id',
            field=models.CharField(auto_created=True, default=xm2cloud_cmp.common.enhance.get_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='region',
            name='id',
            field=models.CharField(auto_created=True, default=xm2cloud_cmp.common.enhance.get_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='script',
            name='id',
            field=models.CharField(auto_created=True, default=xm2cloud_cmp.common.enhance.get_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scriptgroup',
            name='id',
            field=models.CharField(auto_created=True, default=xm2cloud_cmp.common.enhance.get_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scriptlog',
            name='id',
            field=models.CharField(auto_created=True, default=xm2cloud_cmp.common.enhance.get_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scriptlog',
            name='sevent_uuid',
            field=models.CharField(blank=True, default=xm2cloud_cmp.common.enhance.get_uuid, max_length=36),
        ),
        migrations.AlterField(
            model_name='taskworkflow',
            name='id',
            field=models.CharField(auto_created=True, default=xm2cloud_cmp.common.enhance.get_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timedtask',
            name='sevent_uuid',
            field=models.CharField(auto_created=True, default=xm2cloud_cmp.common.enhance.get_uuid, editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='updatelog',
            name='id',
            field=models.CharField(auto_created=True, default=xm2cloud_cmp.common.enhance.get_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='updatelog',
            name='sevent_uuid',
            field=models.CharField(blank=True, default=xm2cloud_cmp.common.enhance.get_uuid, max_length=36),
        ),
        migrations.AlterField(
            model_name='workflowtask',
            name='id',
            field=models.CharField(auto_created=True, default=xm2cloud_cmp.common.enhance.get_uuid, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
