# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-17 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0021_auto_20180717_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardscreen',
            name='parent',
        ),
    ]
