# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-17 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0022_remove_dashboardscreen_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardscreentarget',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.DashBoardScreenTarget'),
        ),
    ]
