# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-18 09:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0023_dashboardscreentarget_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardscreentarget',
            name='hosts',
            field=models.ManyToManyField(blank=True, null=True, to='xm2cloud_cmp.Host'),
        ),
    ]
