# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-18 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0024_dashboardscreentarget_hosts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboardscreentarget',
            old_name='target',
            new_name='metric',
        ),
        migrations.AddField(
            model_name='dashboardscreentarget',
            name='aggregators',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
