# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-18 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0025_auto_20180718_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardscreentarget',
            name='is_compared',
            field=models.BooleanField(default=False),
        ),
    ]
