# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-18 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0026_dashboardscreentarget_is_compared'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardscreentarget',
            name='weight',
            field=models.SmallIntegerField(default=0),
        ),
    ]
