# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-19 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0028_auto_20180718_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboardscreentarget',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='dashboardscreentarget',
            name='parent',
        ),
        migrations.AddField(
            model_name='dashboardscreentarget',
            name='metrics',
            field=models.TextField(default=''),
        ),
    ]
