# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-19 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0030_auto_20180719_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardscreentarget',
            name='screen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.DashBoardScreen'),
        ),
    ]
