# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-23 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0031_auto_20180719_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboardscreentarget',
            options={'ordering': ['-weight']},
        ),
    ]
