# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-25 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0032_auto_20180723_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostgroup',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.Cluster'),
        ),
    ]
