# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-26 14:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import xm2cloud_cmp.common.enhance


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xm2cloud_cmp', '0033_auto_20180725_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmStrategy',
            fields=[
                ('id', models.CharField(auto_created=True, default=xm2cloud_cmp.common.enhance.get_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('rules', models.TextField(default='')),
                ('cycle', models.IntegerField(blank=True, default=5)),
                ('times', models.SmallIntegerField(blank=True, default=3)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.SmallIntegerField(choices=[(0, '\u505c\u6b62'), (1, '\u542f\u7528')], default=1)),
                ('level', models.SmallIntegerField(blank=True, choices=[(1, '\u63d0\u793a'), (2, '\u6b21\u8981'), (3, '\u91cd\u8981'), (4, '\u7d27\u6025')], default=3)),
                ('hosts', models.ManyToManyField(blank=True, null=True, to='xm2cloud_cmp.Host')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlarmStrategyGroup',
            fields=[
                ('id', models.CharField(auto_created=True, default=xm2cloud_cmp.common.enhance.get_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('hosts', models.ManyToManyField(blank=True, null=True, to='xm2cloud_cmp.Host')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
