# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-26 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import xm2cloud_cmp.common.enhance


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0034_alarmstrategy_alarmstrategygroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSubscriber',
            fields=[
                ('id', models.CharField(auto_created=True, default=xm2cloud_cmp.common.enhance.get_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('terminal', models.TextField()),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('protocol', models.CharField(choices=[('sms', '\u77ed\u4fe1'), ('email', '\u90ae\u4ef6'), ('http', 'HTTP'), ('https', 'HTTPS')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='MessageTopic',
            fields=[
                ('id', models.CharField(auto_created=True, default=xm2cloud_cmp.common.enhance.get_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='messagesubscriber',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.MessageTopic'),
        ),
        migrations.AddField(
            model_name='alarmstrategy',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.MessageTopic'),
        ),
    ]
