# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-26 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0035_auto_20180726_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmstrategy',
            name='alarmstrategygroups',
            field=models.ManyToManyField(blank=True, null=True, to='xm2cloud_cmp.AlarmStrategyGroup'),
        ),
    ]
