# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-27 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0037_remove_alarmstrategygroup_hosts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmstrategy',
            name='cycle',
        ),
        migrations.RemoveField(
            model_name='alarmstrategy',
            name='times',
        ),
    ]
