# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-28 09:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0039_auto_20180728_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmstrategy',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='alarmstrategy',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='alarmstrategy',
            name='topic',
        ),
    ]
