# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-28 09:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0040_auto_20180728_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmstrategy',
            name='alarmstrategygroups',
        ),
        migrations.RemoveField(
            model_name='alarmstrategy',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='alarmstrategy',
            name='hosts',
        ),
        migrations.RemoveField(
            model_name='alarmstrategy',
            name='name',
        ),
        migrations.RemoveField(
            model_name='alarmstrategy',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='alarmstrategy',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='alarmstrategy',
            name='update_time',
        ),
    ]
