# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-28 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0042_remove_alarmstrategy_grade'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlarmStrategy',
        ),
    ]
