# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-28 10:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import xm2cloud_cmp.common.enhance


class Migration(migrations.Migration):

    dependencies = [
        ('djcelery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xm2cloud_cmp', '0043_delete_alarmstrategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmStrategy',
            fields=[
                ('periodictask_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djcelery.PeriodicTask')),
                ('sevent_uuid', models.CharField(auto_created=True, default=xm2cloud_cmp.common.enhance.get_uuid, editable=False, max_length=36, unique=True)),
                ('rules', models.TextField(default='')),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('grade', models.SmallIntegerField(blank=True, choices=[(1, '\u63d0\u793a'), (2, '\u6b21\u8981'), (3, '\u91cd\u8981'), (4, '\u7d27\u6025')], default=3)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('djcelery.periodictask',),
        ),
    ]
