# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-28 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import xm2cloud_cmp.common.enhance


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0047_alarmstrategy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acknowledge',
            fields=[
                ('id', models.CharField(auto_created=True, default=xm2cloud_cmp.common.enhance.get_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('message', models.TextField()),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('ack_choices', models.SmallIntegerField(choices=[(0, '\u5355\u4e2a\u786e\u8ba4'), (1, '\u786e\u8ba4\u6240\u6709')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AlarmHistory',
            fields=[
                ('id', models.CharField(auto_created=True, default=xm2cloud_cmp.common.enhance.get_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('create_time', models.DateTimeField(auto_created=True, blank=True, default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('update_time', models.DateTimeField(auto_now_add=True)),
                ('alarmstrategy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.AlarmStrategy')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.Host')),
            ],
        ),
        migrations.AddField(
            model_name='acknowledge',
            name='alarmhistory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.AlarmHistory'),
        ),
    ]
