# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-01 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0048_auto_20180728_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmhistory',
            name='error',
            field=models.TextField(default=''),
        ),
    ]
