# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-06 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xm2cloud_cmp', '0050_auto_20180801_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmstrategy',
            name='alarmstrategygroups',
        ),
        migrations.AddField(
            model_name='alarmstrategy',
            name='alarmstrategygroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='xm2cloud_cmp.AlarmStrategyGroup'),
        ),
    ]
